require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');
const Coupon = require('../models/Coupon');

const products = [
  { name: 'Sony WH-1000XM5 Wireless Headphones', description: 'Industry-leading noise cancellation with 30-hour battery life. Crystal clear calls and superior sound quality.', price: 24999, originalPrice: 32999, discount: 24, category: 'electronics', brand: 'Sony', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500', rating: 4.8, reviewCount: 2847, featured: true, badge: 'Best Seller', tags: ['headphones','wireless','noise-cancelling','sony'] },
  { name: 'Apple iPad Air 11" M2 Chip', description: 'Supercharged by M2. Brilliant 11-inch Liquid Retina display, 256GB storage, all-day battery.', price: 69999, originalPrice: 74999, discount: 7, category: 'electronics', brand: 'Apple', image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500', rating: 4.9, reviewCount: 1203, featured: true, badge: 'New', tags: ['ipad','apple','tablet','m2'] },
  { name: 'Samsung 55" 4K QLED Smart TV', description: '4K QLED display with Quantum HDR, built-in Alexa, and Samsung Gaming Hub.', price: 54999, originalPrice: 74999, discount: 27, category: 'electronics', brand: 'Samsung', image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500', rating: 4.6, reviewCount: 892, featured: true, badge: '27% Off', tags: ['tv','samsung','4k','smart-tv'] },
  { name: 'boAt Airdopes 141 TWS Earbuds', description: 'True wireless earbuds with 42-hour total playback, Beast Mode low latency, IPX4 water resistance.', price: 1299, originalPrice: 4490, discount: 71, category: 'electronics', brand: 'boAt', image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500', rating: 4.2, reviewCount: 15430, featured: false, badge: '71% Off', tags: ['earbuds','tws','boat','wireless'] },
  { name: 'Canon EOS R50 Mirrorless Camera', description: '24.2 MP APS-C sensor, 4K video, Dual Pixel CMOS AF II, ideal for creators and vloggers.', price: 64999, originalPrice: 69999, discount: 7, category: 'electronics', brand: 'Canon', image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500', rating: 4.7, reviewCount: 445, featured: false, badge: '', tags: ['camera','canon','mirrorless','photography'] },
  { name: 'Logitech MX Master 3S Mouse', description: 'Advanced wireless mouse with MagSpeed scrolling, 8K DPI sensor, quiet clicks, USB-C charging.', price: 8495, originalPrice: 9999, discount: 15, category: 'electronics', brand: 'Logitech', image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500', rating: 4.8, reviewCount: 3201, featured: false, badge: '', tags: ['mouse','logitech','wireless','productivity'] },
  { name: 'Atomic Habits — James Clear', description: 'The number 1 New York Times bestseller on building good habits and breaking bad ones.', price: 449, originalPrice: 799, discount: 44, category: 'books', brand: 'Penguin', image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500', rating: 4.9, reviewCount: 8921, featured: true, badge: 'Bestseller', tags: ['self-help','habits','productivity','non-fiction'] },
  { name: 'The Psychology of Money', description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel.', price: 399, originalPrice: 650, discount: 39, category: 'books', brand: 'Jaico', image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500', rating: 4.8, reviewCount: 5640, featured: true, badge: 'Top Rated', tags: ['finance','money','psychology','non-fiction'] },
  { name: 'Rich Dad Poor Dad', description: 'What the rich teach their kids about money. A personal finance classic by Robert Kiyosaki.', price: 299, originalPrice: 395, discount: 24, category: 'books', brand: 'Manjul', image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500', rating: 4.7, reviewCount: 12055, featured: false, badge: '', tags: ['finance','wealth','investing','classic'] },
  { name: 'Sapiens: A Brief History of Humankind', description: 'Yuval Noah Harari explores how Homo sapiens came to dominate Earth.', price: 499, originalPrice: 699, discount: 29, category: 'books', brand: 'Vintage', image: 'https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=500', rating: 4.8, reviewCount: 7832, featured: false, badge: '', tags: ['history','science','anthropology','non-fiction'] },
  { name: 'Allen Solly Men Slim Fit Chinos', description: 'Premium cotton-blend slim-fit chinos. Wrinkle-resistant, versatile for office and casual wear.', price: 1499, originalPrice: 2499, discount: 40, category: 'clothing', brand: 'Allen Solly', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500', rating: 4.3, reviewCount: 2103, featured: false, badge: '40% Off', tags: ['chinos','men','office-wear','cotton'] },
  { name: "Levi's 511 Slim Fit Jeans", description: 'Classic slim fit from hip to ankle. Flexible stretch denim for all-day comfort.', price: 2499, originalPrice: 3999, discount: 38, category: 'clothing', brand: "Levi's", image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500', rating: 4.5, reviewCount: 4521, featured: true, badge: 'Top Pick', tags: ['jeans','levis','slim-fit','denim'] },
  { name: 'Nike Dri-FIT Running T-Shirt', description: 'Sweat-wicking Dri-FIT technology keeps you dry. Lightweight breathable design for performance training.', price: 1295, originalPrice: 1695, discount: 24, category: 'clothing', brand: 'Nike', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500', rating: 4.4, reviewCount: 3891, featured: false, badge: '', tags: ['tshirt','nike','running','dri-fit'] },
  { name: 'Fabindia Cotton Handloom Kurta', description: 'Handcrafted cotton kurta with traditional block print. Comfortable for daily and festive wear.', price: 1999, originalPrice: 2799, discount: 29, category: 'clothing', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=500', rating: 4.6, reviewCount: 1234, featured: false, badge: '', tags: ['kurta','cotton','ethnic','fabindia'] },
  { name: 'Instant Pot Duo 7-in-1 Pressure Cooker', description: '7-in-1 multi-use cooker. Pressure cooker, slow cooker, rice cooker, steamer, saute, yoghurt maker and warmer.', price: 7999, originalPrice: 11995, discount: 33, category: 'home-kitchen', brand: 'Instant Pot', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500', rating: 4.7, reviewCount: 6721, featured: true, badge: 'Best Seller', tags: ['pressure-cooker','instant-pot','kitchen','cooking'] },
  { name: 'Dyson V12 Detect Slim Cordless Vacuum', description: 'Laser dust detection, LCD screen, 60-min battery. Cleans fine dust you cannot normally see.', price: 54900, originalPrice: 62900, discount: 13, category: 'home-kitchen', brand: 'Dyson', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500', rating: 4.8, reviewCount: 892, featured: false, badge: '', tags: ['vacuum','dyson','cordless','cleaning'] },
  { name: 'Philips Air Fryer HD9252 4.1L', description: 'Rapid Air Technology for up to 90% less fat. 4.1L capacity, 7 preset programmes.', price: 9999, originalPrice: 14995, discount: 33, category: 'home-kitchen', brand: 'Philips', image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500', rating: 4.5, reviewCount: 4312, featured: true, badge: '33% Off', tags: ['air-fryer','philips','kitchen','healthy-cooking'] },
  { name: 'Waterproof Mattress Protector', description: 'Waterproof, hypoallergenic fitted protector. Keeps your mattress fresh and clean.', price: 2999, originalPrice: 3999, discount: 25, category: 'home-kitchen', brand: 'Saatva', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500', rating: 4.4, reviewCount: 1087, featured: false, badge: '', tags: ['mattress','bedding','protector','home'] },
  { name: 'Yonex Astrox 88S Pro Badminton Racket', description: 'Head-heavy balance for steep attack. Namd graphite technology for flexible powerful smashes.', price: 8999, originalPrice: 11999, discount: 25, category: 'sports', brand: 'Yonex', image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500', rating: 4.7, reviewCount: 1203, featured: true, badge: 'Top Pick', tags: ['badminton','yonex','racket','sports'] },
  { name: 'Adidas Ultraboost 22 Running Shoes', description: 'Incredible energy return with Boost midsole. Primeknit upper adapts to your foot for long-distance running.', price: 12999, originalPrice: 17999, discount: 28, category: 'sports', brand: 'Adidas', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500', rating: 4.6, reviewCount: 2876, featured: true, badge: '', tags: ['shoes','adidas','running','ultraboost'] },
  { name: 'Strauss Yoga Mat 6mm Anti-Slip', description: 'Premium TPE yoga mat with alignment lines. 6mm thick for joint protection. Includes carry strap.', price: 799, originalPrice: 1299, discount: 38, category: 'sports', brand: 'Strauss', image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500', rating: 4.3, reviewCount: 5432, featured: false, badge: '', tags: ['yoga','mat','fitness','strauss'] },
  { name: 'Nivia Storm Football Size 5', description: 'PU outer casing. Machine-stitched for consistent flight. Ideal for training and match play.', price: 699, originalPrice: 999, discount: 30, category: 'sports', brand: 'Nivia', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500', rating: 4.4, reviewCount: 3201, featured: false, badge: '', tags: ['football','soccer','nivia','sports'] },
  { name: 'LEGO Technic Bugatti Bolide 42151', description: '905 pieces. Moveable pistons, iconic Bugatti livery. For ages 10 and up. Stunning display model.', price: 6999, originalPrice: 8999, discount: 22, category: 'toys', brand: 'LEGO', image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500', rating: 4.9, reviewCount: 743, featured: true, badge: 'Fan Favourite', tags: ['lego','technic','building','bugatti'] },
  { name: 'Hot Wheels Ultimate Garage Playset', description: '4-feet tall, 140+ cars capacity, motorised lift, spiral loops and shark. The ultimate Hot Wheels experience.', price: 4999, originalPrice: 6999, discount: 29, category: 'toys', brand: 'Hot Wheels', image: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=500', rating: 4.6, reviewCount: 1892, featured: false, badge: '', tags: ['hotwheels','cars','garage','playset'] },
  { name: "Funskool Rubik's Cube 3x3", description: 'The original smooth-turning Rubik Cube. 43 quintillion combinations. Hours of brain-teasing fun.', price: 299, originalPrice: 449, discount: 33, category: 'toys', brand: 'Funskool', image: 'https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=500', rating: 4.5, reviewCount: 9812, featured: false, badge: '', tags: ['rubiks','puzzle','brain-teaser','classic'] }
];

const coupons = [
  { code: 'SCELTA10', discount: 10, type: 'percent', minOrder: 500, maxDiscount: 500, active: true },
  { code: 'SCELTA20', discount: 20, type: 'percent', minOrder: 1000, maxDiscount: 1000, active: true },
  { code: 'FLAT100',  discount: 100, type: 'flat', minOrder: 999, active: true },
  { code: 'FLAT200',  discount: 200, type: 'flat', minOrder: 1999, active: true },
  { code: 'NEWUSER',  discount: 15, type: 'percent', minOrder: 0, maxDiscount: 300, active: true }
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('✅ Connected to MongoDB');
  await Product.deleteMany({});
  await Coupon.deleteMany({});
  await Product.insertMany(products);
  await Coupon.insertMany(coupons);
  console.log(`✅ Seeded ${products.length} products`);
  console.log(`✅ Seeded ${coupons.length} coupons`);
  console.log('\n🎉 Scelta database ready!\n');
  process.exit(0);
}

seed().catch(err => { console.error('❌ Seed failed:', err.message); process.exit(1); });
