require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const newProducts = [
  // ELECTRONICS (8)
  { name: 'Apple MacBook Pro 14" M3 Pro', description: 'Supercharged by M3 Pro chip. 18GB unified memory, 512GB SSD, Liquid Retina XDR display. Built for professionals.', price: 199900, originalPrice: 219900, discount: 9, category: 'electronics', brand: 'Apple', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500', rating: 4.9, reviewCount: 892, featured: true, badge: 'Premium', tags: ['macbook','apple','laptop','m3'] },
  { name: 'Sony A7 IV Full-Frame Mirrorless Camera', description: '33MP BSI CMOS sensor, 4K 60p video, real-time Eye AF, 10fps burst. The ultimate hybrid camera for creators.', price: 229990, originalPrice: 249990, discount: 8, category: 'electronics', brand: 'Sony', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500', rating: 4.8, reviewCount: 445, featured: true, badge: 'Pro', tags: ['sony','camera','mirrorless','fullframe'] },
  { name: 'Samsung Galaxy S24 Ultra', description: '200MP camera, Snapdragon 8 Gen 3, built-in S Pen, 5000mAh battery, titanium frame. The ultimate Android flagship.', price: 134999, originalPrice: 149999, discount: 10, category: 'electronics', brand: 'Samsung', image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500', rating: 4.8, reviewCount: 2341, featured: true, badge: 'Flagship', tags: ['samsung','smartphone','s24','android'] },
  { name: 'Bose QuietComfort Ultra Headphones', description: 'World-class noise cancellation with immersive audio. CustomTune technology personalises sound to your ears.', price: 34900, originalPrice: 39900, discount: 13, category: 'electronics', brand: 'Bose', image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500', rating: 4.8, reviewCount: 1876, featured: true, badge: 'Best ANC', tags: ['bose','headphones','anc','wireless'] },
  { name: 'Apple Watch Ultra 2', description: 'Rugged titanium case, dual-frequency GPS, 60-hour battery life, depth gauge. Built for extreme adventures.', price: 89900, originalPrice: 99900, discount: 10, category: 'electronics', brand: 'Apple', image: 'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=500', rating: 4.9, reviewCount: 743, featured: false, badge: 'Ultra', tags: ['apple','watch','smartwatch','ultra'] },
  { name: 'LG OLED evo C3 65" 4K TV', description: 'Self-lit OLED pixels, perfect blacks, Dolby Vision IQ, webOS 23, NVIDIA G-Sync compatible. Cinema at home.', price: 179990, originalPrice: 219990, discount: 18, category: 'electronics', brand: 'LG', image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=500', rating: 4.8, reviewCount: 567, featured: false, badge: '18% Off', tags: ['lg','oled','tv','4k'] },
  { name: 'Sony WF-1000XM5 True Wireless Earbuds', description: 'Industry-leading noise cancellation in earbuds. 8 hours battery, crystal-clear calls, Hi-Res Audio wireless.', price: 19990, originalPrice: 24990, discount: 20, category: 'electronics', brand: 'Sony', image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500', rating: 4.7, reviewCount: 3421, featured: false, badge: '20% Off', tags: ['sony','earbuds','tws','anc'] },
  { name: 'DJI Mini 4 Pro Drone', description: '4K/60fps HDR video, omnidirectional obstacle sensing, 34-min flight time, under 249g. No licence required.', price: 76990, originalPrice: 84990, discount: 9, category: 'electronics', brand: 'DJI', image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500', rating: 4.8, reviewCount: 312, featured: false, badge: 'New', tags: ['dji','drone','4k','aerial'] },

  // BOOKS (5)
  { name: 'Zero to One — Peter Thiel', description: 'Notes on startups, or how to build the future. Peter Thiel shares the contrarian thinking behind PayPal and Palantir.', price: 499, originalPrice: 699, discount: 29, category: 'books', brand: 'Virgin Books', image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=500', rating: 4.7, reviewCount: 6234, featured: false, badge: 'Startup Bible', tags: ['startup','entrepreneurship','thiel','non-fiction'] },
  { name: 'The Almanack of Naval Ravikant', description: 'A guide to wealth and happiness. Collected wisdom of Naval Ravikant on building wealth without getting lucky.', price: 399, originalPrice: 599, discount: 33, category: 'books', brand: 'Penguin', image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500', rating: 4.9, reviewCount: 8901, featured: true, badge: 'Must Read', tags: ['wealth','philosophy','naval','non-fiction'] },
  { name: 'Can\'t Hurt Me — David Goggins', description: 'Master your mind and defy the odds. Goggins shares his astonishing life story and reveals the key to unlocking your full potential.', price: 549, originalPrice: 799, discount: 31, category: 'books', brand: 'Lioncrest', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500', rating: 4.8, reviewCount: 11234, featured: false, badge: 'Bestseller', tags: ['mindset','motivation','goggins','self-help'] },
  { name: 'Thinking Fast and Slow — Daniel Kahneman', description: 'Nobel laureate Daniel Kahneman reveals the two systems that drive the way we think and make choices.', price: 599, originalPrice: 899, discount: 33, category: 'books', brand: 'Penguin', image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=500', rating: 4.8, reviewCount: 9876, featured: false, badge: 'Nobel Prize', tags: ['psychology','thinking','kahneman','non-fiction'] },
  { name: 'The 48 Laws of Power — Robert Greene', description: 'Amoral, cunning, ruthless, and instructive. A detailed examination of the use of power through history.', price: 699, originalPrice: 999, discount: 30, category: 'books', brand: 'Profile Books', image: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=500', rating: 4.7, reviewCount: 14532, featured: false, badge: 'Classic', tags: ['power','strategy','greene','non-fiction'] },

  // CLOTHING (5)
  { name: 'Loro Piana Cashmere Sweater', description: 'Pure Grade-A cashmere from Inner Mongolia. Exceptional softness, warmth without weight. Timeless luxury knitwear.', price: 45000, originalPrice: 55000, discount: 18, category: 'clothing', brand: 'Loro Piana', image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500', rating: 4.9, reviewCount: 234, featured: true, badge: 'Luxury', tags: ['cashmere','luxury','sweater','italian'] },
  { name: 'Canada Goose Expedition Parka', description: 'Rated to -30°C. Arctic-tech shell, coyote fur trim, down fill power 625. The gold standard of extreme cold outerwear.', price: 89000, originalPrice: 99000, discount: 10, category: 'clothing', brand: 'Canada Goose', image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=500', rating: 4.8, reviewCount: 456, featured: false, badge: 'Arctic Grade', tags: ['parka','winter','canada-goose','luxury'] },
  { name: 'Uniqlo Merino Wool Turtleneck', description: 'Extra-fine merino wool, machine washable. Supremely soft, temperature-regulating, minimal and refined.', price: 3990, originalPrice: 4990, discount: 20, category: 'clothing', brand: 'Uniqlo', image: 'https://images.unsplash.com/photo-1608744882201-52a7f7f3dd60?w=500', rating: 4.6, reviewCount: 5678, featured: false, badge: 'Top Pick', tags: ['merino','wool','uniqlo','turtleneck'] },
  { name: 'Rolex Submariner Watch Strap — Rubber B', description: 'FKM rubber strap for Rolex Submariner. Vulcanised rubber, titanium buckle, made in France. Luxury accessory.', price: 18000, originalPrice: 22000, discount: 18, category: 'clothing', brand: 'Rubber B', image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=500', rating: 4.7, reviewCount: 189, featured: false, badge: '', tags: ['watch-strap','rolex','rubber','luxury'] },
  { name: 'Ray-Ban Meta Smart Glasses Wayfarer', description: 'Open-ear audio, 12MP camera, IPX4 water resistant. Stay connected hands-free with iconic Wayfarer style.', price: 29990, originalPrice: 34990, discount: 14, category: 'clothing', brand: 'Ray-Ban', image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500', rating: 4.5, reviewCount: 678, featured: false, badge: 'Smart', tags: ['rayban','smartglasses','meta','wearable'] },

  // HOME & KITCHEN (5)
  { name: 'Vitamix A3500 Ascent Blender', description: 'Smart blending with touchscreen controls, wireless connectivity, 5 programme settings. Professional-grade performance.', price: 54900, originalPrice: 64900, discount: 15, category: 'home-kitchen', brand: 'Vitamix', image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500', rating: 4.9, reviewCount: 1234, featured: true, badge: 'Pro Grade', tags: ['vitamix','blender','kitchen','premium'] },
  { name: 'Le Creuset Signature Cast Iron Dutch Oven 5.3L', description: 'Enamelled cast iron. Superior heat distribution and retention. Dishwasher safe. Lifetime guarantee. Made in France.', price: 32000, originalPrice: 38000, discount: 16, category: 'home-kitchen', brand: 'Le Creuset', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500', rating: 4.9, reviewCount: 2341, featured: false, badge: 'Lifetime Warranty', tags: ['le-creuset','dutch-oven','cast-iron','french'] },
  { name: 'Nespresso Vertuo Next Coffee Machine', description: 'Centrifusion technology for perfect crema every time. Bluetooth connectivity, 5 cup sizes, sustainable aluminium pods.', price: 14990, originalPrice: 18990, discount: 21, category: 'home-kitchen', brand: 'Nespresso', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500', rating: 4.7, reviewCount: 3456, featured: false, badge: '21% Off', tags: ['nespresso','coffee','machine','premium'] },
  { name: 'Dyson Purifier Hot+Cool HP07', description: 'Purifies, heats and cools. HEPA H13 filtration captures 99.97% of particles. Jet Focus Control, Air Multiplier tech.', price: 54900, originalPrice: 64900, discount: 15, category: 'home-kitchen', brand: 'Dyson', image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500', rating: 4.7, reviewCount: 876, featured: false, badge: '', tags: ['dyson','purifier','heater','cooler'] },
  { name: 'Saatva Classic Luxury Firm Mattress Queen', description: 'Dual coil construction, organic cotton cover, lumbar zone support. Hotel-quality sleep at home. 365-night trial.', price: 89900, originalPrice: 109900, discount: 18, category: 'home-kitchen', brand: 'Saatva', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500', rating: 4.8, reviewCount: 2987, featured: false, badge: '365 Night Trial', tags: ['mattress','saatva','luxury','sleep'] },

  // SPORTS (4)
  { name: 'Peloton Bike+ Smart Exercise Bike', description: 'Auto-follow resistance, rotating 24" HD touchscreen, Apple GymKit, immersive classes. Transform your home workout.', price: 179900, originalPrice: 199900, discount: 10, category: 'sports', brand: 'Peloton', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500', rating: 4.8, reviewCount: 1234, featured: true, badge: 'Premium', tags: ['peloton','bike','fitness','smart'] },
  { name: 'Garmin Fenix 7X Pro Solar Smartwatch', description: 'Solar-powered GPS multisport watch. 28-day battery, topographic maps, health monitoring, military-grade durability.', price: 89990, originalPrice: 99990, discount: 10, category: 'sports', brand: 'Garmin', image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500', rating: 4.8, reviewCount: 987, featured: false, badge: 'Solar', tags: ['garmin','smartwatch','gps','multisport'] },
  { name: 'Lululemon Surge Shorts 6"', description: 'Swift fabric, 4-way stretch, sweat-wicking liner. Built for running, training or any high-intensity activity.', price: 7490, originalPrice: 8990, discount: 17, category: 'sports', brand: 'Lululemon', image: 'https://images.unsplash.com/photo-1562886812-41775a01195d?w=500', rating: 4.6, reviewCount: 4321, featured: false, badge: '', tags: ['lululemon','shorts','running','athletic'] },
  { name: 'TaylorMade Stealth 2 Driver', description: '60X Carbon Twist Face, Nanotexture cover, Thru-Slot Speed Pocket. Maximum distance and forgiveness off the tee.', price: 45000, originalPrice: 52000, discount: 13, category: 'sports', brand: 'TaylorMade', image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=500', rating: 4.7, reviewCount: 543, featured: false, badge: 'Pro Choice', tags: ['golf','driver','taylormade','premium'] },

  // TOYS (3)
  { name: 'LEGO Icons Eiffel Tower 10307', description: '10,001 pieces. 1.5 metres tall. The most detailed LEGO set ever made. A true collector\'s masterpiece for adults.', price: 44999, originalPrice: 52999, discount: 15, category: 'toys', brand: 'LEGO', image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500', rating: 4.9, reviewCount: 1876, featured: true, badge: 'Collector\'s Edition', tags: ['lego','icons','eiffel','collector'] },
  { name: 'Razer DeathAdder V3 Pro Gaming Mouse', description: 'Focus Pro 30K optical sensor, 90-hour battery, HyperSpeed wireless, ultra-lightweight 64g design for esports.', price: 14999, originalPrice: 17999, discount: 17, category: 'toys', brand: 'Razer', image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500', rating: 4.8, reviewCount: 3456, featured: false, badge: 'Esports', tags: ['razer','gaming','mouse','wireless'] },
  { name: 'Nintendo Switch OLED Model', description: '7-inch OLED screen, enhanced audio, 64GB storage, wide adjustable stand. Play at home or on the go.', price: 29999, originalPrice: 34999, discount: 14, category: 'toys', brand: 'Nintendo', image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=500', rating: 4.9, reviewCount: 8765, featured: true, badge: 'Fan Favourite', tags: ['nintendo','switch','oled','gaming'] }
];

async function seedMore() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('✅ Connected to MongoDB');
  await Product.insertMany(newProducts);
  const total = await Product.countDocuments();
  console.log(`✅ Added ${newProducts.length} new products`);
  console.log(`✅ Total products in database: ${total}`);
  console.log('\n🎉 Done!\n');
  process.exit(0);
}

seedMore().catch(err => { console.error('❌ Failed:', err.message); process.exit(1); });
